version: '3'
services:
 db:
   image: mysql:5.6.49
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: root
   ports:
     - "6306:3306"
   volumes:
     - mysql_data:/var/lib/mysql
 web:
   build: .
   command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
   volumes:
     - .:/real
   ports:
     - "3000:3000"
   depends_on:
     - db
   tty: true
   stdin_open: true

volumes:
  mysql_data:
